version: 2

sources:
  - name: raw_data
    description: "raw source for orders data"
    database: "{{ env_var('GCP_PROJECT_ID', '') }}" # bq - project id
    schema: "{{ env_var('GCP_BQ_DATASET', 'chilean_public_market') }}" # bq - dataset name
    tables:
      - name: raw_orders